// HingeHelperSource.swift
//
// The C source of the guest-side helper HingeControl compiles on first use.
// Kept as a string rather than a resource file so the shipped sipi stays a
// single binary with nothing to locate at run time.
//
// ── Attribution ──────────────────────────────────────────────────────────────
// Derived from `hinge` (https://github.com/artemnovichkov/hinge) by Artem
// Novichkov, MIT License. The load-bearing details — HID usage page 0xFF61 /
// usage 0x5B, the four-key payload dictionary, IOCFSerialize's binary format,
// and HID client type 4 (the one backboardd accepts without the
// `com.apple.private.hid.client.admin` entitlement) — come from that project.
// See THIRD_PARTY_LICENSES.md for the full license text.
// ─────────────────────────────────────────────────────────────────────────────

extension HingeControl {
    static let helperSource = #"""
// sipi hinge helper — runs INSIDE the iOS Simulator via `simctl spawn`.
//
// Posts the vendor-defined HID event that Device Hub's hinge slider sends, which
// is the only way anything outside SpringBoard can fold a simulated iPhone Duo.
//
// Derived from `hinge` (https://github.com/artemnovichkov/hinge) by Artem
// Novichkov, MIT License. Generated by sipi; edits here are overwritten.
//
//   hinge_helper set   <degrees>
//   hinge_helper sweep <from> <to> <seconds>
#include <CoreFoundation/CoreFoundation.h>
#include <mach/mach_time.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

typedef struct __IOHIDEvent *IOHIDEventRef;
typedef struct __IOHIDEventSystemClient *IOHIDEventSystemClientRef;

extern IOHIDEventRef IOHIDEventCreateVendorDefinedEvent(
    CFAllocatorRef allocator, uint64_t timeStamp, uint32_t usagePage, uint32_t usage,
    uint32_t version, const uint8_t *data, CFIndex length, uint32_t options);
extern IOHIDEventSystemClientRef IOHIDEventSystemClientCreateWithType(
    CFAllocatorRef allocator, int type, CFDictionaryRef properties);
extern void IOHIDEventSystemClientDispatchEvent(
    IOHIDEventSystemClientRef client, IOHIDEventRef event);
extern CFDataRef IOCFSerialize(CFTypeRef object, CFOptionFlags options);

enum {
    kUsagePage = 0xFF61,
    kUsage = 0x5B,
    // Type 4 is the one backboardd accepts from an unentitled process. Types 0-3
    // are refused with "missing the 'com.apple.private.hid.client.admin'
    // entitlement", and that entitlement cannot be granted: CoreSimulator will
    // not spawn or launch a binary that claims it.
    kClientTypeSimple = 4,
    // IOCFSerialize's binary format. A plain binary plist is NOT accepted.
    kSerializeBinary = 1,
    kSweepHz = 60,
};

static void send_angle(IOHIDEventSystemClientRef client, double degrees) {
    if (degrees < 0) degrees = 0;
    if (degrees > 180) degrees = 180;

    CFNumberRef value = CFNumberCreate(NULL, kCFNumberDoubleType, &degrees);
    const void *keys[] = { CFSTR("provider"), CFSTR("source"), CFSTR("type"), CFSTR("value") };
    const void *values[] = {
        CFSTR("com.apple.Virtualization"), CFSTR("hinge-slider-control"), CFSTR("range"), value
    };
    CFDictionaryRef payload = CFDictionaryCreate(
        NULL, keys, values, 4, &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
    CFDataRef data = IOCFSerialize(payload, kSerializeBinary);

    if (data) {
        IOHIDEventRef event = IOHIDEventCreateVendorDefinedEvent(
            NULL, mach_absolute_time(), kUsagePage, kUsage, 0,
            CFDataGetBytePtr(data), CFDataGetLength(data), 0);
        if (event) {
            IOHIDEventSystemClientDispatchEvent(client, event);
            CFRelease(event);
        }
        CFRelease(data);
    }
    CFRelease(payload);
    CFRelease(value);
}

static int usage_message(void) {
    fprintf(stderr,
            "usage: hinge_helper set <degrees>\n"
            "       hinge_helper sweep <from> <to> <seconds>\n");
    return 64;
}

int main(int argc, char **argv) {
    if (argc < 3) return usage_message();

    IOHIDEventSystemClientRef client =
        IOHIDEventSystemClientCreateWithType(NULL, kClientTypeSimple, NULL);
    if (!client) {
        fprintf(stderr, "hinge helper: could not create a HID event system client\n");
        return 1;
    }

    if (strcmp(argv[1], "set") == 0 && argc == 3) {
        send_angle(client, atof(argv[2]));
    } else if (strcmp(argv[1], "sweep") == 0 && argc == 5) {
        double from = atof(argv[2]), to = atof(argv[3]);
        double seconds = atof(argv[4]);
        if (seconds < 0) seconds = 0;
        int steps = (int)fmax(1, round(seconds * kSweepHz));
        for (int i = 0; i <= steps; i++) {
            send_angle(client, from + (to - from) * i / steps);
            if (i < steps) usleep((useconds_t)(seconds * 1e6 / steps));
        }
    } else {
        return usage_message();
    }

    // Let the event system deliver before the process exits and its client goes
    // away; without this a single `set` can be dropped.
    usleep(100000);
    return 0;
}
"""#
}
